### ISSUE TITLE
Large LastSeen time discrepency vs the admin console

### ISSUE THREAD

**Issue by deckarep** [tailscale/tailscale-client-go#65]
Hello,

This is very useful client library, thanks for this and the larger Tailscale product which is truly amazing.

One quick question: Upon comparing the results from this client (via the tailscale api) I'm noticing the `LastSeen` field on the `Devices` struct seems to be heavily cached or outdated vs what shows in the admin console.

If this is a reasonable request: would it be possible to have the `LastSeen` value recent enough so that applications can basically also show a `connected` status when the time delta is small enough just like the official TailScale admin console is showing in the `LastSeen` column?

As a side note: If I make a change to my tailnet such as to bring a machine online or offline it seems that such an action causes the api data to flush from the cache and I can get a recent LastSeen but then it gets outdated again with no API, tailnet manipulation.

**Comment by knyar** [comment]
Hey, thank you for filing an issue about this. `LastSeen` is there to be able to tell when a node that is currently offline was last connected (see https://github.com/tailscale/tailscale/issues/2107 for some historic context).

https://github.com/tailscale/tailscale/issues/2107 is an issue tracking a feature request to expose whether a device is currently online or offline in the Devices API - we will update that issue when we have something to share here.

Since it's not something specific to `tailscale-client-go`, I am going to close this issue now. Thanks again!
